title: Dennis Ried - Music Research
description: Music Research, TEI/MEI Coding, XQuery & XSLT Development
baseurl: ""
url: "https://riedde.github.io/personal-website"

markdown: kramdown
highlighter: rouge
show_page_titles: false

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md